version: '3'
services:
  postgres:
    image: postgres:14.2
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "car_store_db"
      POSTGRES_USER: "car_user"
      POSTGRES_PASSWORD: "123"